on: 
  push:
    paths : 
      - .github/workflows/download_and_save_to_git_container.yaml
#  schedule:
#    - cron: "5 * * * *"
jobs:
  job1:
    runs-on: ubuntu-latest
    container: morglum/monrstudio
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}    
    steps:
      - uses: actions/checkout@v2
#      - name: dont install libraries, taken care by docker image 
#        run: |
#          install.packages("janitor")
#          install.packages("sessioninfo")
#          install.packages("kableExtra")
#          install.packages("mapview")
#        shell: Rscript {0}
      - name: download csv and date_Added column
        run: |
          Rscript R/download_and_upload_to_git.R
#      - name: Update report  (this code works, but not used)
#        run: |
#          Rscript -e 'rmarkdown::render("R/test_report.Rmd")'          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add "data/list_of_date_added.csv"|| echo "No changes to commit"
          git add "data/well_tag_number*.zip"|| echo "No changes to commit"
          git add "R/test_report.html"|| echo "No changes to commit"
          git add "R/test_github_report.md"|| echo "No changes to commit"
          git add 'R/test_github_report_files/*' || echo "No changes to commit"
          git commit -am "add data - automatic update"|| echo "No changes to commit"
          git push origin|| echo "No changes to commit"
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}          