on: 
#  push:
  schedule:
    - cron: "0 23 * * *"
jobs:
  job1:
    runs-on: ubuntu-latest
#    container: rocker/geospatial
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies for curl
        run: |
          sudo apt-get install libcurl4-openssl-dev          
      - name: Install libraries
        run: |
          install.packages("dplyr")
          install.packages("janitor")
          install.packages("readr")
          install.packages("httr")
          install.packages("sessioninfo")
        shell: Rscript {0}
      - name: download csv and upload to s3
        run: |
          Rscript R/download_and_upload_to_git.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'data/list_of_date_added.csv' || echo "No changes to commit"
          git commit -ma 'data/*' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}          